version: 2.1

jobs:
  failure:
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - run: exit 1
      - run:
          name: Fail
          command:  echo "Hiii"
          when: on_fail
    
workflows:
  fail-workflow:
    jobs:
      - failure
